### ISSUE TITLE
Api limit

### ISSUE THREAD

**Issue by FeliksMarello** [kutovoys/xray-checker#14]
Доброго времени суток, есть ли еще какие-то сервисы которые я могу указать в конфиге для мониторинга?

На ipinfo попадаешь на лимиты и в логах появляеться ошибка:
xray-checker  |   "status": 429,
xray-checker  |   "error": {
xray-checker  |     "title": "Rate limit exceeded",
xray-checker  |     "message": "You've hit the daily limit for the unauthenticated API.  Create an API access token by signing up to get 50k req/month."

**Comment by kutovoys** [comment]
Да их довольно много.
ifconfig.me
ifconfig.co
Или можно развернуть свое где либо на базе ifconfig.io

**Comment by FeliksMarello** [comment]
Спасибо за информацию!
